Date::DATE_FORMATS[:default] = "%d/%m/%Y"
Date::DATE_FORMATS[:dasherize] = "%d-%m-%Y"
Date::DATE_FORMATS[:formal] = "%d %B %Y"
Time::DATE_FORMATS[:default] = "%d/%m/%Y"
Time::DATE_FORMATS[:date_time] = "%a %b %d, %Y at %H:%M"
